<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Portfolio 5 - Pixar Films</title>

<script src="site_libs/header-attrs-2.29/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Portfolio</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="about.html">About</a>
</li>
<li>
  <a href="p01.html">Portfolio 1</a>
</li>
<li>
  <a href="p02.html">Portfolio 2</a>
</li>
<li>
  <a href="p03.html">Portfolio 3</a>
</li>
<li>
  <a href="p04.html">Portfolio 4</a>
</li>
<li>
  <a href="p05.html">Portfolio 5</a>
</li>
<li>
  <a href="p06.html">Portfolio 6</a>
</li>
<li>
  <a href="p07.html">Portfolio 7</a>
</li>
<li>
  <a href="p08.html">Portfolio 8</a>
</li>
<li>
  <a href="p09.html">Portfolio 9</a>
</li>
<li>
  <a href="p10.html">Portfolio 10</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Portfolio 5 - Pixar Films</h1>

</div>


<blockquote>
<p>The goal here is to explore the Pixar Films data from TidyTuesday and
see if I can find anything of interest.</p>
</blockquote>
<pre class="r"><code>##install.packages(&quot;pixarfilms&quot;)</code></pre>
<pre class="r"><code>library(&quot;pixarfilms&quot;)
library(tidyr)
library(dplyr)</code></pre>
<pre><code>## 
## Attaching package: &#39;dplyr&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     filter, lag</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     intersect, setdiff, setequal, union</code></pre>
<pre class="r"><code>pixar &lt;- pixar_films</code></pre>
<div id="runtime-trends" class="section level2">
<h2>Runtime Trends</h2>
<pre class="r"><code>mean(pixar$run_time, na.rm = TRUE)</code></pre>
<pre><code>## [1] 104.84</code></pre>
<p>The average runtime for a Pixar film is around 105 minutes - how has
that changed over time?</p>
<pre class="r"><code>library(ggplot2)</code></pre>
<pre class="r"><code>pixar %&gt;%  
  ggplot(aes(x = release_date, y = run_time)) +
  geom_line() +
  geom_point() +
  labs(title = &quot;Pixar Film Runtimes Over Time&quot;, x = &quot;Year&quot;, y = &quot;Run Time &quot;)</code></pre>
<pre><code>## Warning: Removed 2 rows containing missing values or values outside the scale range
## (`geom_point()`).</code></pre>
<p><img src="p05_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>It appears that there was a large spike shortly after 2021 - I am
curious to know which movie had such a long run time.</p>
<pre class="r"><code>ggplot(pixar, aes(x = reorder(film, run_time), y = run_time)) +
  geom_col() +
  coord_flip() +
  labs(title = &quot;Pixar Film Runtimes&quot;, x = &quot;Film&quot;, y = &quot;Run Time&quot;)</code></pre>
<pre><code>## Warning: Removed 2 rows containing missing values or values outside the scale range
## (`geom_col()`).</code></pre>
<p><img src="p05_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<pre class="r"><code>pixar[which.max(pixar$run_time), ]</code></pre>
<pre><code>## # A tibble: 1 × 5
##   number film  release_date run_time film_rating
##   &lt;chr&gt;  &lt;chr&gt; &lt;date&gt;          &lt;dbl&gt; &lt;chr&gt;      
## 1 27     &lt;NA&gt;  2023-06-16        155 Not Rated</code></pre>
<pre class="r"><code>pixar[which.min(pixar$run_time), ]</code></pre>
<pre><code>## # A tibble: 1 × 5
##   number film      release_date run_time film_rating
##   &lt;chr&gt;  &lt;chr&gt;     &lt;date&gt;          &lt;dbl&gt; &lt;chr&gt;      
## 1 1      Toy Story 1995-11-22         81 G</code></pre>
<p>Apparently Luca has an extremely long run time, compared to the other
Pixar films… perhaps I have to watch it now…</p>
<p>Toy Story has the shortest run time - remains superior though…</p>
</div>
<div id="rating-trends" class="section level2">
<h2>Rating Trends</h2>
<p>Let’s see how run time varies by rating</p>
<pre class="r"><code>pixar %&gt;%
  group_by(film_rating) %&gt;%
  summarise(mean_runtime = mean(run_time), count = n())</code></pre>
<pre><code>## # A tibble: 4 × 3
##   film_rating mean_runtime count
##   &lt;chr&gt;              &lt;dbl&gt; &lt;int&gt;
## 1 G                   100.    13
## 2 N/A                  NA      3
## 3 Not Rated           155      1
## 4 PG                  101.    10</code></pre>
<p>The majority of the movies are G rated and have an average run time
of around 100 mins followed by PG rated moves with a similar run time
(avg of 101). Not extremely surprised by these results. Let’s plot this
…</p>
<pre class="r"><code>pixar %&gt;%  
  ggplot(aes(x = film_rating, fill = film_rating)) +
  geom_bar() +
  labs(title = &quot;Distribution of Film Ratings&quot;, x = &quot;Rating&quot;, y = &quot;Count&quot;)</code></pre>
<p><img src="p05_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>I am curious to know if ratings have become “less restrictive” or
rather if more movies have been made recently that have more “severe”
ratings</p>
<pre class="r"><code>pixar %&gt;%  
  ggplot(aes(x = release_date, y = film_rating, color = film_rating)) +
  geom_point() +
  labs(title = &quot;Pixar Film Runtimes Over Time&quot;, x = &quot;Release Date&quot;, y = &quot;Film Rating&quot;)</code></pre>
<p><img src="p05_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<p>Not particularly informative, but it does look like most early films
were G rated where as around 2005 it looks like PG movies were
introduced.</p>
</div>
<div id="years-since-release" class="section level2">
<h2>Years Since Release</h2>
<pre class="r"><code>library(lubridate)</code></pre>
<pre><code>## 
## Attaching package: &#39;lubridate&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     date, intersect, setdiff, union</code></pre>
<pre class="r"><code>pixarnew &lt;- pixar %&gt;%
  mutate(years_since_release = year(Sys.Date()) -  year(release_date))</code></pre>
<pre class="r"><code>pixarnew %&gt;%
  group_by(film_rating) %&gt;%
  summarise(mean_years_old = mean(years_since_release, na.rm = TRUE))</code></pre>
<pre><code>## # A tibble: 4 × 2
##   film_rating mean_years_old
##   &lt;chr&gt;                &lt;dbl&gt;
## 1 G                    18.3 
## 2 N/A                   3.33
## 3 Not Rated             2   
## 4 PG                   10.4</code></pre>
<p>The G rated films on average tend to be older than the PG rated
films.</p>
<p>Let’s see if films are getting shorter or longer…</p>
<pre class="r"><code>ggplot(pixarnew, aes(x = years_since_release, y = run_time)) +
  geom_point() +
  geom_smooth(method = &quot;lm&quot;, se = FALSE) +
  labs(title = &quot;Do Pixar Films Get Longer Over Time?&quot;, y = &quot;RunTime&quot;, x = &quot;Years Since Release&quot;)</code></pre>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<pre><code>## Warning: Removed 2 rows containing non-finite outside the scale range
## (`stat_smooth()`).</code></pre>
<pre><code>## Warning: Removed 2 rows containing missing values or values outside the scale range
## (`geom_point()`).</code></pre>
<p><img src="p05_files/figure-html/unnamed-chunk-15-1.png" width="672" />
It looks like no - Pixar films have not gotten longer over time, rather
more recent movies appear to be longer, but I am curious to see this
without the two “outliers”</p>
<pre class="r"><code>pixarfilter &lt;- pixarnew %&gt;%  
  filter(run_time &lt; 130)</code></pre>
<pre class="r"><code>ggplot(pixarfilter, aes(x = years_since_release, y = run_time)) +
  geom_point() +
  geom_smooth(method = &quot;lm&quot;, se = FALSE) +
  labs(title = &quot;Do Pixar Films Get Longer Over Time?&quot;, y = &quot;RunTime&quot;, x = &quot;Years Since Release&quot;)</code></pre>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="p05_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<p>Still appears to be a negative relationship!</p>
<p>Overall, I think this was a fun little experiment. However, I was
hoping that there was going to be more to the data like info about
characters(male/female/other? animal/human? princess? etc.), themes of
plots, viewer ratings, directors, or funding. Nevertheless, explored the
data and made some cool graphs!</p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
